#ifndef _SLATE_VIXEN_CONFIG_H_
#define _SLATE_VIXEN_CONFIG_H_

#define VERBOSE_INIT ENABLE
#define VERBOSE_TEST ENABLE

#define INIT_OK "[+] INITIATED DRIVER FOR %s."

// WHEEL !! TODO !!
#define WHEEL_CIRCUMFERENCE 1

// MOTORS !! TODO !!
#define MOTOR_GPIO_PWM_LEFT  PORT::D, 7
#define MOTOR_GPIO_DIR_LEFT  PORT::D, 6
#define MOTOR_GPIO_PWM_RIGHT PORT::D, 5
#define MOTOR_GPIO_DIR_RIGHT PORT::D, 4

// INCEREMENTAL ENCODERS !! TODO !!
#define INCREMENTAL_ENCODER_PULSES_PER_ROTATION 360
#define INCREMENTAL_ENCODER_GPIO_LEFT  PORT::B, 0
#define INCREMENTAL_ENCODER_GPIO_RIGHT PORT::B, 1

#endif
