# PROJECT DIRS
DIRS_INC:=inc /usr/avr/include
DIR_SRC :=src
DIR_OBJ :=obj
DIR_DEP :=dep
DIR_BIN :=bin

# PROJECT FILES
ELF:=$(DIR_BIN)/firmware.elf
HEX:=$(DIR_BIN)/firmware.hex
BIN:=$(DIR_BIN)/firmware.bin
ASM:=$(DIR_BIN)/firmware.asm

# LIB DIRS
DIR_FOSL   :=$(HOME)/Documents/libs
DIR_LIB    :=$(DIR_FOSL)/EMBEDDED/AVR
DIR_LIB_INC:=$(DIR_LIB)/inc
DIR_LIB_LIB:=$(DIR_LIB)/lib

# LIBS AND DEFS
LIBS:=
DEFS:=

# TARGET
MCU     :=atmega328p
F_CPU   :=10000000
TIO_BAUD:=9600
PROG    :=arduino
PORT    :=/dev/ttyUSB0

# TOOLCHAIN
TOOLCHAIN:=avr-
CC     :=$(TOOLCHAIN)gcc
CXX    :=$(TOOLCHAIN)g++
ASMC   :=$(TOOLCHAIN)gcc
LD     :=$(TOOLCHAIN)g++
OBJCOPY:=$(TOOLCHAIN)objcopy
OBJDUMP:=$(TOOLCHAIN)objdump
SIZE   :=$(TOOLCHAIN)size
STRIP  :=$(TOOLCHAIN)strip

# COMPILER FLAGS
WARNING     :=-Wall -Wextra -pedantic -Wno-write-strings
OPTIMIZATION:=-O3 -Os -fdata-sections -ffunction-sections -fno-exceptions -s
